### ISSUE TITLE
Discovering the providers

### ISSUE THREAD

**Issue by heruan** [vaadin/auth#10]
Most of the difficulties with this project will come from dealing with the peculiarities of each provider, their Spring libraries and different choice they made implementing the OIDC protocol.

It'd be risky to choose one provider, write all the code for it, and then find ourselves in trouble at week 5 since what we've done doesn't work for the other two providers.

Let's start understanding each of them, hands-on, before diving into the actual implementation. For each of them:

- Get a working instance of the provider (e.g. a local Keycloak instance, a free trial for Azure…)
- Download a plain starter app from start.vaadin.com
- Add the provider's Spring add-on as a dependency
- Read the add-on documentation
- Configure the add-on to be redirected to the provider's login page

**Comment by gtzluis** [comment]
https://docs.google.com/document/d/19AhAqMwR8H356KZwXBhaTpBW6rUwN8FhPvqxSpB0F4I/edit

**Comment by heruan** [comment]
After prototyping the authentication flow for all the three selected providers, turns out that for a plain Spring app (e.g. MVC) it is easy to configure OIDC for authentication but in a Vaadin app there are a lot of details to be taken into account such as bundle endpoints, heartbeats, etc.

This add-on should make configuration easier and straightforward, possibly with reasonable defaults to make it really work out-of-the-box. To achieve this, we might want to produce a single artifact to enable SSO according to the provided Spring configuration, and then only if needed introduce additional provider’s specific features to the provider’s specific modules.

It seems reasonable to base the add-on on the latest Spring add-on for Flow (23.2-SNAPSHOT) which already includes the new Spring component-based security configuration (see PR 14303). Flow Spring add-on provides the `ViewAccessChecker` API which takes care of redirecting the browser to the login page for protected views.

Authentication with SSO opens up two different alternatives in this regard:
1. Have a LoginView in the Vaadin app which contains an explicit link to the provider’s SSO URL
2. Do not have a local login page, but immediately redirect to the provider’s login page

Option 1 would let mixed authentication mechanism and providers, e.g. in-app form login or different SSO (e.g. Azure + Google). Option 2 can be used when authentication happens only with a single SSO provider.

This add-on can provide an (overridable) default configuration which creates a login page (mapped to the /login route) with links to all the configured providers.
